site_name: FAIRiCUBE-HUB - Getting started, Examples & How To's
#site_url: https://fairicube.readthedocs.io
#repo_url: https://github.com/fairicube/fairicubehub-doc
#edit_uri: edit/main/docs
copyright: Copyright © 2023-2024 by the FAIRiCUBE Team
theme: readthedocs  # alternative: mkdocs readthedocs

nav:
  - OVERVIEW:
    - FAIRiCUBE Digital Library: index.md
    - About FAIRiCUBE project: overview/about_fic.md
    - FAIRiCUBE Hub: overview/fic_hub.md
    - FAIRiCUBE Hub platform: overview/fic_platform.md
    - GeoDataCubes: overview/geodatacubes.md
    - Machine Learning: overview/machine_learning.md
  - FAIRiCUBE USECASES:
    - UC1 - Urban climate change: use_cases/uc1_urban_climate.md
    - UC2 - Biodiversity and agriculture: use_cases/uc2_biodiversity_agri.md
    - UC3 - Drosophila Genetics: use_cases/uc3_drosophila_genetics.md
    - UC4 - Neighbourhood building stock: use_cases/uc4_buildings.md
    - UC5 - Biodiversity occurrence cubes: use_cases/uc5_biodiversity_cubes.md
  - User guide:
    - Introduction: user_guide/ug_introduction.md
    - FAIRiCUBE Catalog: user_guide/fic_catalog.md
    - FAIRiCUBE Query Tool: user_guide/query_tool.md
    - User and access management: user_guide/user_access_management.md
    - Adding Datasets to FAIRiCUBE: user_guide/adding_datasets.md
    - Adding Analysis and Processing resources to FAIRiCUBE: user_guide/adding_ap.md
    - FAIRiCUBE EOX Lab: user_guide/eox_lab.md
    - FAIRiCUBE Storage: user_guide/storage.md
    - FAIRiCUBE Rasdaman Datacubes: user_guide/rasdaman_platform.md
    - FAIRiCUBE Rasdaman Lab: user_guide/rasdaman_lab.md
    - FAIRiCUBE Labs examples: user_guide/lab_examples.md
    - FAIRiCUBE Web Map: user_guide/fic_visualization.md
    - How to contribute to this documentation: user_guide/howto_readthedocs.md
    - How to reuse the FAIRiCUBE approach: user_guide/fic_approach.md
    - Further information: user_guide/further-information.md
  - Self-Training:
    - Introduction: self_training/st_introduction.md
    - Pre-Processing: self_training/pre_processing.md
    - Machine Learning: self_training/st_machine_learning.md
    - Deep Learning: self_training/deep_learning.md
    - GeoDataCubes: self_training/st_geodatacubes.md
    - xcube: self_training/xcube.md
    - EO-College - Cube & Clouds: self_training/eo_cubes_clouds.md
  - AI TOOLKIT:
    - Introduction: ai_toolkit/ai_introduction.md
    - Getting started with AI-toolkit: ai_toolkit/ai_toolkit_getting_started.md
    - AI-toolkit examples: ai_toolkit/ai_toolkit_examples.md
    - Introduction to scikit-learn: ai_toolkit/scikit_introduction.md
    - Getting started with scikit-learn: ai_toolkit/scikit_getting_started.md
    - Scikit-learn examples: ai_toolkit/scikit_examples.md
    - Introduction to TensorFlow: ai_toolkit/tf_introduction.md
    - Getting started with TensorFlow: ai_toolkit/tf_getting_started.md
    - TensorFlow examples: ai_toolkit/tf_examples.md
    - Introduction to PyTorch: ai_toolkit/pt_introduction.md
    - Getting started with PyTorch: ai_toolkit/pt_getting_started.md
    - PyTorch examples: ai_toolkit/pt_examples.md
    - Introduction to MLflow: ai_toolkit/mlflow_introduction.md
    - Introduction to TensorBoard: ai_toolkit/tb_introduction.md
  - GEODATACUBES TOOLKIT: 
    - Introduction: gdc_toolkit/gdc_introduction.md
    - GDAL: gdc_toolkit/gdal.md
    - Rasterio: gdc_toolkit/rasterio.md
    - Xarray: gdc_toolkit/xarray.md
  - LESSONS LEARNT AND TIPS&TRICKS:
    - Introduction: lessons_learnt_tips_tricks/ll_introduction.md
    - How to speed-up NetCDF data loading and processing time on cloud environments: lessons_learnt_tips_tricks/climate_data_processing_with_dask_extremly_slow.md
    - How to transform a GeoTiff file into a Cloud-Optimised-Geotiff: lessons_learnt_tips_tricks/from_tiff_to_cog.md
    - How to check if a PyTorch installation is present and working: lessons_learnt_tips_tricks/pytorch_verification.md
    - How to generate a GeoTIFF file from a NumPy array: lessons_learnt_tips_tricks/geotiff_generation.md
    - How to create binary layers from data layer in QGIS: lessons_learnt_tips_tricks/binary_layers_from_data_layers.md
    - How to download genomic data from Drosophila via Jupyter Notebook: lessons_learnt_tips_tricks/Drosophila_data_via_Jupyter_Notebook.md
    - How to access and download Copernicus point data with the CDS API: lessons_learnt_tips_tricks/How_to_Copernicus_point_data_with_CDS_API.md
  - EXTERNAL RESOURCES:
    - EOxHub / EuroDataCube: external_resource/edc_access.md
    - Copernicus Hub: external_resource/copernicus_hub.md 
    - Sentinel-Hub: external_resource/sentinelhub_access.md


plugins:
  - search
  - mkapi

markdown_extensions:
  - toc:
      permalink: "#"
      baselevel: 2
  - attr_list
